baseURL = "/"
title   = "by2kaapi"
locale = "en-us"

# Enable relative and canonical URLs
relativeURLs = true
canonifyURLs = true

# Use module imports instead of 'theme = "..."'
[module]
  [[module.imports]]
    path = "github.com/satiyap/kaapi"

[params]
  tagline = "Morning coffee, brewed and filtered."
  author  = "@satiyap"
  github  = "https://github.com/satiyap"
  favicon = "/logo.png"
